import java.math.BigInteger;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;

public class sha1 {

    public static String h1(String input)
    {
        try {

            MessageDigest md=MessageDigest.getInstance("SHA-1");
            byte[] messageDigest=md.digest(input.getBytes());
            BigInteger no= new BigInteger(1,messageDigest);
            String hashtext=no.toString(16);
            while(hashtext.length()<32)
            {
                hashtext="0"+hashtext;
            }
            return hashtext;
        }
        catch(NoSuchAlgorithmException e)
        {
            throw new RuntimeException(e);
        }
    }

    public static void main(String args[])throws NoSuchAlgorithmException
    {

        System.out.println("Hash code generated by SHA-1 ");
        String s1="Computer Networks";
        System.out.println("\n"+s1+" : "+h1(s1));

        String s2="HEllo world";
        System.out.println("\n"+s2+" : "+h1(s2));
    }



}



